In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import dataset
movies = pd.read_csv(r"C:\Users\Rajashri\Desktop\Resume\Resume Projects\Movie Recommender\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\Rajashri\Desktop\Resume\Resume Projects\Movie Recommender\tmdb_5000_credits.csv")

In [3]:
print(movies.shape)
movies.head(5)

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
print(credits.shape)
credits.head(5)

(4803, 4)


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

#### Merge the dataframes

In [5]:
movies = movies.merge(credits, how='inner', on='title')
print(movies.shape)

(4809, 23)


In [6]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4809 non-null   int64  
 1   genres                4809 non-null   object 
 2   homepage              1713 non-null   object 
 3   id                    4809 non-null   int64  
 4   keywords              4809 non-null   object 
 5   original_language     4809 non-null   object 
 6   original_title        4809 non-null   object 
 7   overview              4806 non-null   object 
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object 
 10  production_countries  4809 non-null   object 
 11  release_date          4808 non-null   object 
 12  revenue               4809 non-null   int64  
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object 
 15  status               

In [8]:
# Drop all the unnecessary columns
movies = movies.drop(columns=['budget','homepage','id','original_language','original_title','production_companies',
                              'production_countries','runtime','spoken_languages','status','tagline','vote_count',
                              'popularity','release_date','revenue','vote_average'], axis=1)
print(movies.shape)
movies.head(3)

(4809, 7)


genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                      title  movie_id  \
0                                    Avatar     19995   
1  Pirates of the Caribbean: At World's End       285   
2                                   Spectre    206647   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [9]:
# Re-ordering the columns
movies = movies.reindex(['movie_id','title','overview','keywords','genres','cast','crew'], axis='columns')
print(movies.shape)
movies.head(3)

(4809, 7)


movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [10]:
# Let's check if any null values are present
movies.isnull().sum()

movie_id    0
title       0
overview    3
keywords    0
genres      0
cast        0
crew        0
dtype: int64

In [11]:
# There are 3 missing values in 'overview', so let's drop it
movies.dropna(inplace=True)

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
keywords    0
genres      0
cast        0
crew        0
dtype: int64

In [13]:
# Let's check if any duplicate values are present
movies.duplicated().sum()

0

### Feature Engineering

In [14]:
# Let's explore the 'genres' column
movies['genres'].value_counts()

[{"id": 18, "name": "Drama"}]                                                                                                                                             371
[{"id": 35, "name": "Comedy"}]                                                                                                                                            282
[{"id": 18, "name": "Drama"}, {"id": 10749, "name": "Romance"}]                                                                                                           164
[{"id": 35, "name": "Comedy"}, {"id": 10749, "name": "Romance"}]                                                                                                          144
[{"id": 35, "name": "Comedy"}, {"id": 18, "name": "Drama"}]                                                                                                               142
                                                                                                                                  

In [15]:
import ast

def convert_genre(obj):
    genre = []
    for i in ast.literal_eval(obj):
        genre.append(i["name"])
    return genre

movies['genres'] = movies['genres'].apply(convert_genre)

In [16]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [17]:
# Let's explore the 'keywords' column
movies['keywords'].value_counts()

[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  411
[{"id": 10183, "name": "independent film"}]                                                                                                                                                                                                                                                                                                                                                                     

In [18]:
def convert_keyword(obj):
    words = []
    for i in ast.literal_eval(obj):
        words.append(i["name"])
    return words

movies['keywords'] = movies['keywords'].apply(convert_keyword)

In [19]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [20]:
# Let's explore the 'cast' column
movies['cast'].value_counts()

[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [21]:
def convert_cast(obj):
    cast = []
    counter = 0
    for i in ast.literal_eval(obj):
        # We need the names of only top 3 actors
        if counter != 3:
            cast.append(i["name"])
            counter += 1
        else:
            break
    return cast

movies['cast'] = movies['cast'].apply(convert_cast)

In [22]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                               cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

In [23]:
# Let's explore the 'crew' column
movies['crew'].value_counts()

[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [24]:
def convert_crew(obj):
    crew = []
    for i in ast.literal_eval(obj):
        # We need the name of the director only
        if i["job"] == "Director":
            crew.append(i["name"])
            break
    return crew

movies['director'] = movies['crew'].apply(convert_crew)

In [25]:
movies = movies.drop(columns=['crew'], axis=1)
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                               cast          director  
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   [James Cameron]  
1     [Johnny Depp, Orlando Bloom, Keira Knightley]  [Gore Verbinski]  
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]      [Sam Mendes]

In [26]:
# Convert the 'overview' column to list too
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                               cast          director  
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   [James Cameron]  
1     [Johnny Depp, Orlando Bloom, Keira Knightley]  [Gore Verbinski]  
2      [Daniel Craig, Christoph Waltz, Léa Seydoux]      [Sam Mendes]

In [28]:
# The next step would be to strip all the spaces between names and keyword instances.
# This is done so that our vectorizer doesn't count the "Johnny" of "Johnny Depp" and "Johnny Galecki" as the same.
# Now when we remove space 'JohnnyDepp' and 'JohnnyGalecki' both are treated as single entities now. No confusion.

In [29]:
# Remove spaces for the concerned columns
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['director'] = movies['director'].apply(lambda x:[i.replace(" ","") for i in x])

In [30]:
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   

                                            cast         director  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]   [JamesCameron]  
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]  [GoreVerbinski]  
2      [DanielCraig, ChristophWaltz, LéaSeydoux]      [SamMendes]

In [31]:
# Concatenate these columns into a single column 'tags', which is a string that contains all the metadata that we want to feed to our vectorizer.
movies['tags'] = movies['overview']+movies['keywords']+movies['genres']+movies['cast']+movies['director']
movies.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   

                                            cast         director  \
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]   [JamesCameron]   
1     [JohnnyDepp, OrlandoBloom, KeiraKnightley]  [GoreVerbinski]   
2      [DanielCraig, ChristophWaltz, LéaSeydoux]      [SamMendes]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...

In [32]:
data = movies[['movie_id','title','tags']]
data.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...

In [33]:
# Convert list to string
data['tags'] = data['tags'].apply(lambda x:" ".join(x))
data.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                                tags  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...

In [34]:
# Convert tags to lowercase
data['tags'] = data['tags'].apply(lambda x:x.lower())
data.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...

In [35]:
data['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron'

### Using CountVectorizer() to extract features from text

In [36]:
# CountVectorizer is used to convert a collection of text documents to a vector of term/token counts.
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=5000,stop_words='english')

# Tokenize and build vocab
vectorizer.fit(data['tags'])

# Print the identified unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'century': 726, 'marine': 2778, 'dispatched': 1273, 'moon': 2985, 'unique': 4698, 'mission': 2952, 'torn': 4555, 'following': 1718, 'orders': 3198, 'protecting': 3514, 'alien': 155, 'civilization': 831, 'cultureclash': 1064, 'future': 1793, 'society': 4145, 'spacetravel': 4183, 'futuristic': 1794, 'romance': 3802, 'space': 4177, 'tribe': 4620, 'soldier': 4150, 'battle': 412, '3d': 35, 'action': 71, 'adventure': 105, 'fantasy': 1609, 'sciencefiction': 3915, 'zoesaldana': 4994, 'sigourneyweaver': 4079, 'captain': 659, 'long': 2671, 'believed': 441, 'dead': 1128, 'come': 899, 'life': 2629, 'headed': 2000, 'edge': 1389, 'earth': 1378, 'turner': 4644, 'elizabeth': 1412, 'quite': 3563, 'ocean': 3159, 'drugabuse': 1342, 'exoticisland': 1543, 'loveofone': 2706, 'slife': 4127, 'traitor': 4592, 'shipwreck': 4050, 'ship': 4049, 'alliance': 162, 'afterlife': 118, 'fighter': 1661, 'pirate': 3359, 'aftercreditsstinger': 117, 'johnnydepp': 2402, 'orlandobloom': 3206, 'keiraknightley': 2

In [37]:
# Encode document
vector = vectorizer.transform(data['tags'])

# Summarize encoded vector
print(vector.shape)
print(vector.toarray())

(4806, 5000)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [38]:
vectorizer.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent'

### Using Stemming() to normalize words to their root forms

In [39]:
# Clearly, there are some issues, like 'action' ~ 'actions' should be same
# So, we will use "Stemming" -> ["likes","liked","likely","liking"] -> ["like"]

In [40]:
# Stemming is the process of producing morphological variants of a root/base word.
import nltk
from nltk.stem import PorterStemmer
 
ps = PorterStemmer()
 
def stem(text):
    list1 = []
    for i in text.split():
        # stem each word
        list1.append(ps.stem(i))
    
    # Convert list to string now
    return " ".join(list1)

data['tags'] = data['tags'].apply(stem)

In [41]:
data.head(3)

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   

                                                tags  
0  in the 22nd century, a parapleg marin is dispa...  
1  captain barbossa, long believ to be dead, ha c...  
2  a cryptic messag from bond’ past send him on a...

In [42]:
data['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [43]:
vectorizer.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent'

### Calculate 'Cosine' Similarity of a movie with every other movie

In [44]:
# Cosine Similarity is a measure of similarity, often used to measure document similarity in text analysis.
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vector)
print(similarity.shape)

(4806, 4806)


In [45]:
# similarity matrix for movie1
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ])

In [46]:
# similarity matrix for movie2
similarity[1]

array([0.08964215, 1.        , 0.0625    , ..., 0.02635231, 0.        ,
       0.        ])

#### Understand how to recommend movies

In [47]:
# Movie Index -> Similarity matrix Index -> Sort -> Fetch movies

In [48]:
# Get index of a movie
s1 = data[data['title'] == 'Batman Begins'].index[0]
s1

119

In [49]:
# Get the list of cosine similarity scores for that particular movie with all movies.
dist = similarity[s1]
dist

array([0.04829453, 0.05050763, 0.07576144, ..., 0.02129589, 0.02380952,
       0.02317449])

In [50]:
# When we will sort the movies, we will lose its index, but we need to maintain its index always
sorted(list(enumerate(dist)), reverse=True)

[(4805, 0.023174488732966077),
 (4804, 0.023809523809523808),
 (4803, 0.021295885499998),
 (4802, 0.0),
 (4801, 0.08425254637422692),
 (4800, 0.0),
 (4799, 0.02486823656509969),
 (4798, 0.035996616477069254),
 (4797, 0.0),
 (4796, 0.038180177416060626),
 (4795, 0.08924214965063204),
 (4794, 0.03688555567816587),
 (4793, 0.10101525445522105),
 (4792, 0.04123930494211613),
 (4791, 0.08099238707340582),
 (4790, 0.02699746235780194),
 (4789, 0.05832118435198043),
 (4788, 0.09832102880166932),
 (4787, 0.03962144258751637),
 (4786, 0.017998308238534627),
 (4785, 0.04517539514526256),
 (4784, 0.038180177416060626),
 (4783, 0.14285714285714285),
 (4782, 0.022875450543583874),
 (4781, 0.1889822365046136),
 (4780, 0.05832118435198043),
 (4779, 0.060914490387317256),
 (4778, 0.05399492471560388),
 (4777, 0.04517539514526256),
 (4776, 0.032773676267223106),
 (4775, 0.11206636293610517),
 (4774, 0.0),
 (4773, 0.07697370086861782),
 (4772, 0.02231053741265801),
 (4771, 0.03571428571428571),
 (4770, 

In [51]:
# Sorting has been done acc. to index, which we don't want, we want ot sort acc. to similarity scores
sorted(list(enumerate(dist)), reverse=True, key=lambda x:x[1])

[(119, 1.0000000000000007),
 (65, 0.3898234515660837),
 (3, 0.3535533905932739),
 (1363, 0.3361990888083155),
 (210, 0.32444284226152503),
 (1362, 0.31298431857438064),
 (4641, 0.2857142857142857),
 (9, 0.2799748199650662),
 (3825, 0.26452002850644324),
 (4071, 0.2584382953523688),
 (428, 0.2525381361380527),
 (1670, 0.24939187455541983),
 (299, 0.24433888871261034),
 (238, 0.23397800710095015),
 (1748, 0.21063136593556736),
 (1250, 0.20857039859669468),
 (3297, 0.20851441405707477),
 (4231, 0.20788767860257112),
 (2261, 0.20526320231631418),
 (808, 0.2020305089104422),
 (3834, 0.19611613513818404),
 (4141, 0.19611613513818404),
 (283, 0.19599838302001008),
 (3948, 0.19287221158731835),
 (252, 0.19262853213235487),
 (1492, 0.19245008972987526),
 (3863, 0.191662969499982),
 (1879, 0.19090088708030312),
 (3733, 0.19090088708030312),
 (2007, 0.19047619047619047),
 (4781, 0.1889822365046136),
 (4148, 0.18898223650461354),
 (1726, 0.18569533817705186),
 (3341, 0.18367346938775508),
 (1400, 

### Recommend Movies 

In [52]:
def recommend(movie):
    # Get index of a movie
    movie_index = data[data['title'] == movie].index[0]
    # To get the distance with every other movie, we need to get its index in the similarity matrix
    distances = similarity[movie_index]
    # Sort the movies acc to similarity
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])
    # Fetch the top 10 similar movies
    movies_list = movies_list[1:11]
    # Get the movie indices and return the corresponding titles
    for i in movies_list:
        movie_indices = i[0]
        print(data['title'].iloc[movie_indices])

In [53]:
recommend("The Avengers")

Avengers: Age of Ultron
Captain America: Civil War
Iron Man 3
Captain America: The First Avenger
Iron Man
Ant-Man
Iron Man 2
Captain America: The Winter Soldier
Guardians of the Galaxy
Thor: The Dark World


### Dump into a pickle file

In [54]:
# dump the data dictionary into a 'pickle' file
import pickle

pickle.dump(data.to_dict(), open(r'C:\Users\Rajashri\Desktop\Resume\Resume Projects\Movie Recommender\movie_dict.pkl', 'wb'))
pickle.dump(similarity, open(r'C:\Users\Rajashri\Desktop\Resume\Resume Projects\Movie Recommender\similarity_matrix.pkl', 'wb'))